/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import java.util.HashMap;
import java.util.Map;

public class Huffman {
  Map<Character, Integer> frequencyDict; // stores frequency of each char

  public static void main(String[] args) {
  }

  public void countFrequencies(String string) {

  }
}
